name: Setup Repo
description: Prepare and install everything for the repo

inputs:
  github-token:
    description: The GitHub token

  pnpm-version:
    description: Version of pnpm to use
    default: "10.12.1"

  node-version:
    description: Version of Node.js to use
    default: "20.19.6"

  eas-version:
    description: Version of EAS CLI to use
    default: "21.4.0"

  expo-version:
    description: Optional legacy Expo CLI version to install

  expo-token:
    description: Expo token to authenticate with
    required: false

runs:
  using: composite
  steps:
    - name: 🏗 Setup pnpm
      uses: pnpm/action-setup@v4
      with:
        version: ${{ inputs.pnpm-version }}

    - name: 🏗 Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: pnpm

    - name: 🏗 Setup Expo
      if: ${{ inputs.expo-token }}
      uses: expo/expo-github-action@v8
      with:
        eas-version: ${{ inputs.eas-version }}
        expo-version: ${{ inputs.expo-version }}
        token: ${{ inputs.expo-token }}
        packager: pnpm

    - name: 📦 Install dependencies
      run: pnpm install --frozen-lockfile
      shell: bash
